use_frameworks!

platform :ios, '8.0'

target 'ALAMuDaoSDK_Example' do
  pod 'ALAMuDaoSDK', :path => '../'

  target 'ALAMuDaoSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
